server:
  port: 8008

spring:
  application:
    name: thicket-stage

  profiles:
    active: localDB

  datasource:
    driver-class-name: ${localDB.driver}
    username: ${localDB.username_}
    password: ${localDB.password}
    url: ${localDB.url}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true